#!/bin/bash
#
# get-ubr
#
# 2024/09/24 Gabriel Moreau <Gabriel.Moreau@univ-grenoble-alpes.fr>
#
# https://learn.microsoft.com/fr-fr/windows/release-health/release-information
# https://learn.microsoft.com/fr-fr/windows/release-health/windows11-release-information

get_ubr () {
	local os=$1
	local version=$2
	local build=$3
	local url=$4

	local ubr=$(curl -s -L "${url}" \
		| grep -A20 "Version ${version} (OS build ${build})" \
		| grep -E '^<td>[[:digit:]][[:digit:]]*\.[[:digit:]][[:digit:]]*</td>' \
		| grep "${build}\." \
		| cut -f 2 -d '.' \
		| cut -f 1 -d '<' \
		| head -1)
	echo "	\$UBR${os}_${version} = ${ubr} # ${version} ${url}"
}

# Windows 10 / version 22H2
get_ubr 10 22H2 19045 'https://learn.microsoft.com/en-us/windows/release-health/release-information'

# Windows 11 / version 23H2
get_ubr 11 23H2 22631 'https://learn.microsoft.com/en-us/windows/release-health/windows11-release-information'

# Windows 11 / version 23H2
get_ubr 11 24H2 26100 'https://learn.microsoft.com/en-us/windows/release-health/windows11-release-information'
