#!/bin/bash

export LANG=C

for search in 'Kasperky-Uninstall-[123456789]*.zip' 'SWMB-WAPT-[123456789]*.zip' 'SWMB-OCS-[123456789]*.zip' 'SWMB-Setup-[123456789]*.exe'
do
	# Find all files, sort by date
	# and keep only the most recent for each day
	find .  -maxdepth 1 -type f -a -name "${search}" -printf "%TY-%Tm-%Td %TT %p\n" | \
	sort | \
	perl -ne '
		BEGIN {
			$previous_date = "";
			$previous_file = "";
		}
		# Capture day date and filename
		if (/^(\d{4}-\d{2}-\d{2}) \S+ (.*)$/) {
			my $current_date = $1;
			my $current_file = $2;

			if ($current_date eq $previous_date) {
				# if date not change, remove previous file
				if (-e $previous_file) {
					print "rm -f $previous_file\n";
				}
			} else {
				# update date
				$previous_date = $current_date;
			}
			# update file
			$previous_file = $current_file;
		}
		'
done
