#!/bin/bash
#
# check-with-swln
#
# 2024/09/24 Gabriel Moreau <Gabriel.Moreau@univ-grenoble-alpes.fr>

SWMB_HOME=${HOME}/resinfo/swmb
[ -d "$1" ] && SWMB_HOME=$1

while [ ! -d "${SWMB_HOME}" ]
do
  read -p "Enter path to the SWMB project: " SWMB_HOME
done

function mydiff () {
  if which meld > /dev/null
  then
    meld $1 $2
  else
    diff --side-by-side $1 $2
  fi
}

for f in check-with-swln install.bat installer.ps1 Makefile post-install-01reg.bat pre-install-01copy.bat uninstall.bat extend-rules.mk extend-variables.mk
do
  cmp -s ${f} ${SWMB_HOME}/dists/swln/${f} || mydiff ${SWMB_HOME}/dists/swln/${f} ${f}
done

cmp -s LocalMachine-Boot.preset        ${SWMB_HOME}/Presets/LocalMachine-All.preset || mydiff ${SWMB_HOME}/Presets/LocalMachine-All.preset LocalMachine-Boot.preset
cmp -s LocalMachine-PostInstall.preset ${SWMB_HOME}/Presets/LocalMachine-All.preset || mydiff ${SWMB_HOME}/Presets/LocalMachine-All.preset LocalMachine-PostInstall.preset
cmp -s CurrentUser-Logon.preset        ${SWMB_HOME}/Presets/CurrentUser-All.preset  || mydiff ${SWMB_HOME}/Presets/CurrentUser-All.preset  CurrentUser-Logon.preset
